<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="EPBYMINW2457" name="com.epam.tat.module4.test.DivDoubleTest" tests="8" failures="0" timestamp="11 Apr 2018 08:23:25 GMT" time="8.078" errors="2">
  <testcase name="divDoubleTest" time="1.015" classname="com.epam.tat.module4.test.DivDoubleTest"/>
  <testcase name="divDoubleTest" time="1.015" classname="com.epam.tat.module4.test.DivDoubleTest"/>
  <testcase name="divDoubleTest" time="1.015" classname="com.epam.tat.module4.test.DivDoubleTest"/>
  <testcase name="divDoubleTest" time="1.001" classname="com.epam.tat.module4.test.DivDoubleTest"/>
  <testcase name="zeroDivisionTest" time="1.001" classname="com.epam.tat.module4.test.DivDoubleTest">
    <error type="org.testng.TestException" message="
Method DivDoubleTest.zeroDivisionTest()[pri:0, instance:com.epam.tat.module4.test.DivDoubleTest@4cdbe50f] should have thrown an exception of type class java.lang.NumberFormatException">
      <![CDATA[org.testng.TestException: 
Method DivDoubleTest.zeroDivisionTest()[pri:0, instance:com.epam.tat.module4.test.DivDoubleTest@4cdbe50f] should have thrown an exception of type class java.lang.NumberFormatException
	at org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:89)
	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1376)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:677)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- zeroDivisionTest -->
  <testcase name="divDoubleTest" time="1.016" classname="com.epam.tat.module4.test.DivDoubleTest"/>
  <testcase name="zeroDivisionTest" time="1.000" classname="com.epam.tat.module4.test.DivDoubleTest">
    <error type="org.testng.TestException" message="
Method DivDoubleTest.zeroDivisionTest()[pri:0, instance:com.epam.tat.module4.test.DivDoubleTest@3ecf72fd] should have thrown an exception of type class java.lang.NumberFormatException">
      <![CDATA[org.testng.TestException: 
Method DivDoubleTest.zeroDivisionTest()[pri:0, instance:com.epam.tat.module4.test.DivDoubleTest@3ecf72fd] should have thrown an exception of type class java.lang.NumberFormatException
	at org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:89)
	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1376)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:677)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1211)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at com.epam.tat.module4.test.runner.TestRunner.main(TestRunner.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
]]>
    </error>
  </testcase> <!-- zeroDivisionTest -->
  <testcase name="divDoubleTest" time="1.015" classname="com.epam.tat.module4.test.DivDoubleTest"/>
</testsuite> <!-- com.epam.tat.module4.test.DivDoubleTest -->
